site_name: Second book
nav:
  - Essential AI Home:
      - 'Essential AI': index.md
      - 'About Me': about.md

  - NNs to LLMs:
      - 'Introduction': nns-to-llms/index.md
      - 'Decision Making and Neurons': nns-to-llms/decision-making-and-nns.md
      - 'Neural Networks': nns-to-llms/neural-networks.md
  
  - Math for ML/DL:
      - 'Introduction': math-for-ml/index.md 
      - 'Gradient Descent': math-for-ml/gradient-descent.md 

  # - AI Papers Explained:
  #     - 'Attention Is All You Need': research/attention-is-all-you-need.md

  # - Publications:
  #     - 'ACM Multimedia 2023': conferences/mmfp3687-anand.md

  # - Mutimodal AI:
  #     - 'Introduction': multimodal-ai/index.md

plugins:
  - search
  - glightbox
  - plotly
  - drawio_file

theme:
  name: material
  font:
    text: Andika

  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.path
    - navigation.prune
    - navigation.top
    - search.highlight
    - search.suggest
    - content.tabs.link
    - content.code.copy
    - navigation.footer
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
        # primary: teal
        # accent: purple

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
        # primary: teal
        # accent: purple
  language: en
  icon:
    annotation: material/plus-circle
    repo: fontawesome/brands/github

repo_url: https://github.com/dsa-book/non-executable
repo_name: dsa-book/non-executable

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - attr_list
  - md_in_html
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

  - pymdownx.superfences:
      custom_fences:
        - name: plotly
          class: mkdocs-plotly
          format: !!python/name:mkdocs_plotly_plugin.fences.fence_plotly

        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
